pipeline {
    agent { label 'docker-agent-dotnet-v8' }

    stages {
        stage('Restore') {
            steps {
                dir('jira-1') {
                    sh 'dotnet restore SimpleConsoleApp.slnx'
                }
            }
        }

        stage('Build') {
            steps {
                dir('jira-1') {
                    sh 'dotnet build SimpleConsoleApp.slnx --configuration Release --no-restore'
                }
            }
        }

        stage('Test') {
            steps {
                dir('jira-1') {
                    sh 'dotnet test SimpleConsoleApp.slnx --configuration Release --no-build --logger "trx;LogFileName=test-results.trx"'
                }
            }
        }
    }

    post {
        success {
            echo 'Build and tests passed!'
        }
        failure {
            echo 'Something went wrong.'
        }
    }
}
