pipeline {
    agent { label 'docker-agent-dotnet-v8' }

    environment {
        IMAGE_NAME = 'simple-console-app'
        IMAGE_TAG = "${BUILD_NUMBER}"
        CONTAINER_NAME = 'simple-console-app-running'
    }

    stages {
        stage('Build Docker Image') {
            steps {
                dir('jira-1') {
                    sh "docker build -t ${IMAGE_NAME}:${IMAGE_TAG} -t ${IMAGE_NAME}:latest ."
                }
            }
        }

        stage('Stop Previous Container') {
            steps {
                sh "docker rm -f ${CONTAINER_NAME} || true"
            }
        }

        stage('Deploy') {
            steps {
                sh "docker run -d --name ${CONTAINER_NAME} ${IMAGE_NAME}:latest"
            }
        }

        stage('Verify') {
            steps {
                sh "docker logs ${CONTAINER_NAME}"
            }
        }
    }

    post {
        success {
            echo 'Build, test, and deploy succeeded!'
        }
        failure {
            echo 'Something went wrong.'
        }
    }
}
